<a href="https://colab.research.google.com/github/vaibhav051422-collab/machine-learning/blob/main/hyperparametertuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:

from google.colab import files

files.upload()

Saving ht.zip to ht (1).zip

{'ht (1).zip': b'PK\x03\x04-\x00\x00\x00\x08\x00\x83\xb53O\xb6\xf5g\x9b\xff\xff\xff\xff\xff\xff\xff\xff\x0c\x00\x14\x00diabetes.csv\x01\x00\x10\x00A]\x00\x00\x00\x00\x00\x00\x06#\x00\x00\x00\x00\x00\x00]\\\xdb\xca&\xc9q\xbc\x17\xec\x9b4?u>\\Z\x18\x1b]\x18\x0b\xec\x17\x90W\x83\xbcH\x9e\x05\xad\xf6\xfd]q\xc8\xeao\xc5\xa2a4\xfduw\x1d23"#\xb3\xfa\x8f\x7f\xff\xf6\x97\xef\x7f\xfa\xfe\xe3O\xdf~y\xfe\xfdo\xbf\xfe\xf8\xf3/\xdf\x9e\xdf\xff\xed\xe7\x9f\xff|.\xfc\xf2\xcb\xaf\x7f\xff\xf6\xfc\xd7_\x7f\xfa\xfe\xdf\xff\xfb\xd3\x8f\x7f\xfd~\xfe\xe1\xf9\xc3\xf7_~\xfd\xdbO\xdf\x9f\xdf\xff\xc7\x1f\x9e\x7f\xfd\xe9O\xff\xf3\xed\x1f\xdf~\xf9\xe3\xb7?\xff\xf4\x97\xbf\x7f\xfb\xf6o\xbf~\xff\xf1\x1f?\xfd\xfc\xfd\xf9\x97\xbf|{\xfe\xf3\xd7\x7f\xfc\xf8\xf3\xff}\xfb\xe1w\xe3\xc9m=\xb3<\xb5?\xe9\xa9\xf5k<\xe9k\x94\xf9\xf4\xf4\xe4\x1f~\x97\x9f\xd5\x9f1\x9e\xb2\xcf\xd52x\xb5\xf6\xfc\xd4\xfc\xa4\x1f~\xb7\x9e\xbc\xea3\xda\xb9v\xae\xd6\xaf\x8a{\xf1\xac\xe2{7\xef\xad\xcfnOY_\xe7\x9e\xaf<\xe6Sx\xf3y~\x9dOKxs\x1e\xebi\xf5\xfc\xa0|\x95\xb5\xce0p\xff\xf9\xe7<\x9e\xe9\xa7w\xbe\xbb\xa4\xf3\xee\x84\xdb\xeb3\x17\x06y\xde\x85;\xf0\xecrfR\x06_}\x1e\x9e;o\xc4\xf39\xb0\\\x1b\xa7\xf1\xc3\xef\xce\xe8\xf6|fzZ\x7fz\xab\xe7\x81_\x1d?\xe8\xe7\x81|\xf3\x99W\xe9\xcf\x1e~\xc0y\xf2yKo\xb8t\xfe8\x0f\xdfEO\x9e\x1cT\xde1(\xbc\xf7L\xc5c\xae\xeb\\\xecg\x92\xb5\xc5\xa0\xea~\x96\x1eZ\xe6\x99n\xfej-?}\xf2\xde\xb3\x98g\xbd\xb0\x90\xcfj\x03\xa3\xc2\xa4\xea>\xa3\xda^\x8f\xb3\x9a\x13\xa3\x7f\xf2\xecX\x12\xbe`\x9d\xcd\xca\xf8\xc1|rJ1i\x0c\xbb\xad\xe6\xbd\xc0z\xac\xf3\xd8\xa7\x9d\xe5\xaf\x98\xb9\xee\xd5V\xfa\xdey\x17{k\xb1\xcf\x94u\xf5\xfc\x91\xb0N\x98\xd2\xd9\xf1\xa6\xad\xc6\xe6\x9f\xad\xd2\xd8\xcfrO\xbe\xf6,[m\xbc\xbf\x9f\xe5\xd6\xeb\xcf\xaa\x9e\x8d9\xfbtf[\xce~\xd7\xcd\x07\xcct\xb6d\xca\x92\xf6\xc6\xf0\xbc_\r\x13_\xdc\xdf\xc4\xb1\x9d\x87nOls\xe4\xed\x8c\xbcqlg12W\x95\x16\x8c\x1d\xfe*\xa3\xe2/\x18\xf8\xf9I\xa3\xfd\xc1\xa6\xb0\xaa\xe3NM\x8b\x86])\x1c;L\xe7\xcc\xa2f\xae{I\xdd/8\xaf?\xab6G\xbc\xbe\xf1\xfec\xbaUKsl\xe9\xec\xcb\xb937zA\xe1\xca\x9fu.\\\x1a\xbc\xb7?K\xdbv\xdeV\n\x7fQ`|\x9c;\xec|^\x93j\xdauX\xcd\xf2\xd5\xb4\x1fl7\x06P\xb9\xaeg\x1e\xc3N\x00\xa3\x9d\x98\xd6\x83\x07\x9e\xb1\xe3\x07\xebL\xad,-<V\xf1\xfc5\xc3~K\xe3\xda\x95\x11\x83\x1bx\xad\xdf\x9c\xf7\xd7\xe6\xa6.\xdckc>?\x9b\xf2.\x18,_\x9e\x0b\xfc&\xd1\x15\x8eQ\x8c\xc4\xa5=\x0f)X\x98}\x96\xc26q\x16\xaf\xae\xbbn^\x17\x05\x1a\xeeZ*\x1c\xf9\xc4\xd5\xc2w\x8fq\xd6\x9c\x0e\\\xb0\xdd\x08\n\x85~\xc4{\xfby\xdb\xb1\x16;a\x86\'\xc0\x9a\x8f\xd9V\xf9\xd2q\xae>ln\xc7\x1eN\\\xd2\xc6V\xee\xd8\xcc\\B\xeeg\xadal-\xf1\xd9ck$r\x04.\xcb\xf1\x17n\xd6\xa4\xff\x9f\x81-\x8f{f\xed#\xd6\x93\x9e\x84\xc7\xcf\x92\x1d!\xce\x03\x8e\xbfFP\x9c2\x97c\x80-9\xeaah\xe7m\x88\xa8gz\xf9k\xed\x8a\x81\xca\xcd\xce\xf4\xfb\x08\'\xc4\xab\xfbx\xc3\xd6y3\xec\x14+V\xe4\xfa\xc3\x1b9\xb5\x17\x03\xfeF#\xa5\x11\xb5\xf6\xe1\xdd\x11\x0e\x11\x18\xea\xf9\x7f\xd8\xae\xf0\xec\x85\xf8 \x1b\xe5x\xdb\x89h6\xdfs=\x13\x0c\xba\x8cL[qVR\x8b\xd9a`\x08\xf2pl\\\xa6\xebb\x9b\x93\x11b\xd2u\xcf\x1e\xd4D3\xc0\xa4\xda\xb1\xc0\xbeb\xb5\xb8\x1e\xb8\x85\xff\xe3\x0ff\xd6\xdec\x00\xb3\xf2\xfd\\\x93\xfa8\xccg\xcf\xfa\xf8\xd91\x93\xb3\x98\xf5\xc4\x92c\x07\xd3\xce-\xd7M\x8c\x88\x18a\xe2\x9e\xb5A\x07\xd8\xa3\x18\xc1\x12W|\x95\xb0\x85\xb3\r_s\x9d\xd0\xd2|\xf5,\xd4\xd0\xd3\xcepZ\x16P\x9c\x11iuJ\x98Q,k\xf3\xc8\x16ml\xda\xa7e\xddg\xdf\xaa\x03\xf9y\xfc\xd0\xb5\xd2\x1f\x85\xf0:\x0cM\x00\x84E\xc88{\\d]\xe3DG\xed\xd7\x99rnX/?\x98\xfe\xdc\xb9X|\xf2\xf9\xe1l6\x11\xbe\x14q\xbb\xc4d6\xb1\xd2\xb7vF\x8a\x8e8C\x8f\xc3e\xc7\x82&\xb3_\x04H\xed\xc2&\x0f8\xd1\x0c?\x17>\xd4J\x0fS(\xc02v\xfag\x82u:\x96l\xc7\xf7\xc2\x7f\x86\x9d$Z\x83Vd!\x10-c[\xa5\xd3T\x87\xd1\xc57\xb4\x1cN\x9b\x05!\x06\x81\x03@\x8d\xebV=q\xac\xd6\x99\x1c\x9f_&1\x84A\xbc\xd2,eF\x8c\xa2\x9e<F\xbf\xc7\xb5\xf1\x04\xef.\xdc\x0f\xd9\xdfY\xe3p\xac\xc1\x10\xe85\xe3\xb47\xa1\x87\xc6\x7fV\x05|\xa7>)\x8c\xefD\x11M\x19h\x9f\x9f;\xde"\x0b(\x0eo\xf9\x84\xd1\xa1\x01\xc8\x06\xea\x89c\xda\xe23\xd33\xdbc"\x19\x8f=\x11\xa8}\x0e\xa8\x04H\xcb\xe4\x10Ec\xa4\x8b\x9c\xe8\xbc\x01\xa1\xce\x08;\xc2\xb2\x12\x1d\xf9\x04\xd8\xb24M\xc2`\r$\xe8dc9i\xa6m\xc9\xb0`\xb23\x06\x9chY\x9bpY\x8b\xedry\xb6\xd8\x9fDv\x02\x83\t\x98\xcdg<\x02\x0b\x1b\xc0bH\xce\x08\xe9\x9c4\x82\xa8\xf6\x17\x03\x18\x8c\xd6z\x17c:HY\xbd@\x0b\x862`}\x0f\xb9(]q\xbc\x81\xec\x04\xb1\xae \x97\x15\xff\xe0\x17rG\x98\x87\xa2\\g@\xa2\x014P?;\xd5qy\x0c\x95vp\x82\x04\xa3\xc8\xc8\x0eA\xd8\x89\x16\xce|\x00\x9eK3\'\x83\x8a\\\xb60v.B\x8e\x03\xd8\xb9[\xef\x06\xc3\xe6\xdd\xd8\xfd\x02r\xabhp\xc6*H \x02\x1f+\xe3\xc6\x18\xc1s\xbd\xd3:\xab\xd5@\xb4\x01\x96%)\xbe\x96\x08@\xc7#\x18\x1d\xab\xe0n\xc9\x04\xfb\xb8V\x0f\x04?N\x03Bp\xec\xbb\tS*v0\x88\xddx\xe3\xd4\xd9\xdb\xb3\xe7\xc5\xfc\xfb\\;\xb7\rY\xdaYon\xc7\xf1\xa2\x12\xe1\xe4\xe5\xc8E\xd1\xa4`\x16\xd9\xbbA\x80\xce\\T\'\x0ee\xc5\xac\n\xd3\x8a\xee\xb7\xf2\xe2\xaeaIt\xf4\xce\x9c#\xf7\x12\x93Z)\xdfg\x9f\xb7\xe6R\xe2\xcd\x04\xd8\x14n\xd7\xb8\xdc\x9d$\x86\x91dkhk\x1a\xe0+\xfc\xa4\x93\xd4d\xc4Y\xfaI\x05\xb6u\xcd\xeb\xf84"\x19\xf1\xae\x1a\xbf\x1b\x9dS\xd4bf\xfb|\x06\x935\x15V\x80\xce\x8c\xfcgg\xb1\x10\x07\xd3\xce\xa3H>\x90e\x88\xd80)\x82\x05\x02\xad\xb0\xdb\x85w\x17oX\xc35C\x03\xefD\xb0\xd1\xc0\x8e\x1f\x9e\xbd\xe8b\xf4\x8cd_\xc2\x8eeXQ\x10\x0e\x1e\xa9\'wD\xd5\xec\x08{\x06\x18\x99\t\'U\x1c\xfa;m\xdf1N\x00=\xfa\x1b\xda\xf7tV\xc2\xb0\x1c\x9eS\xec\x1a\x9b\xd39~\x05\x13s\x98\x83y\x06\xbc\x0e\xb2<\xf0\xb2\xe3\xff]?\x98\x87 \x89\xf1\x0c29\xc4\xfd\xcda\xe9\xfeq\xcd\xc4II\x15\x90;=m\x80\xd9\x1aQ\xab\xdc\x8cJ\xe0\x9e\x0f\n\x8c\xed\xb7\x1f?z\t(\xc9\x03"\xa4\xcd[Xx\x9c\xf7\xcc\x01\x91\xe3\xd0\x9e\xe1\x00\r\xb4INh\xb0\xcdM\x80\xd5z\x10\x9b\xcc\x84\nf4\x94]\xe8\xe9\xe3\xc5\x1b\x90zp\xe9F\xfe\x7f\xa6\xc67\x1c8n)\xa8I\x0f\xfaph"\x1e?\x0f\xac\x8c\xc0\xb3C2&\xe8\t3J\x93\xc1z\x9e/\xe7\xdc\xf4\x80\xfe1\xb7\x93\xb6\xe4\xe6\xab\xb0RF\x04\xc6\xf7\xfbv\x04\x86\x9ad\xa5\x8b\xc6@\x84:\xc1\xb8rr$(\x8aH\x83\x91\xf6\x0c\xf6\xec\x94\x12\xa2\xd1\xa6cu\xa1\xeb\xc3&\x12]\xac*$&\xe7\xe1A\xbb\x94R18)\xd9\xdco\xea\xbf\x998 \x80\\\x07\xef\xb5|\x84\x96\x9b\'\xdb\x90g\xaa\xa6\xc1\x9d\x0b\x87x\x8a\xec\x12^*\xae\x01\x9bZrp0\'c\xb6\x07_\xcelz\x8f\xdb\xc9\xf8\xaa\x83\x8f\xa2\xc3p\xbaU\x88\x81\x9d\xee;j\xd0\xa4z\xf6\xda\\!\xf1\x07/\x01SnQ^\x1e\xd2\xc9\xed@<\x98}\x0b-\xb0\x0f5\x96\xa60\x9d\xab\x8f\x10\xbc\xcf\x08\x9a\x1b\t!\x12Y\xa7D\\\xd4\xb3\x13"\x1b\x85\x037E\xca[\xfe\x9f\xcf\xfb\x85a]Y\xeao\xbc\xb8\x00\x92\x0c\xbf\x9b\x1b\x92\xa7\xac\xadr\xbf\xfaK\xf2+\x95\x96\x8e=m\x11\xf5\xeae\x9dM\xac\xb3\xc7\x92\xd2\x17\xce~)\xa2"N\x0f\x92/\x05?\xc6\xd4L\xf6\xd7J I\xc5\x9a\x83C/\xe0\x9ed\xa6\x15\xab\x02|\xbb[\xd6\xe4\x0cT\x87j\xe4\x08Ty\xc0\xca\xa9\t(?\x8eLqc\xbfN\x04\xda-x\xcd\xa8\xf3\x82\x05hmg\x82\x02G>\x84\x1a\xe6\xb4\x8e\x9f\xe8\xd5|\xf0\x99\xfaY\xd1^\xcd\x99K\x80\\\x9e\x81\x8f\xc8\x002\x928\x11\xd7s\xa1E*z\x02\x1f(-i\x95\xdc\x14\xe9^\x8d\\3\x91\xb15\xf9\xfbYYF\xb8\xb3\xc8\xadG\x8cj\xdct\xc072\x03!\xc2\x08<3qj\x0e\xc0\x11\x07\xd6\x1ba+#\x99}e0\x8cT\xeb.\x88\xba\xf4\xf3\xbc\xb8GE9\xfe,\xc5\tR\xa5\xfc7\x04~a\xed\xa5\x8f\x1b\xde\x11\x06\x87]I@=\xcfz\xd6k\x15\xe9\xba\x82\xad\x82\xdc\xd3n\x98\xb92\x99\x04\xfax\xb92\xcb\xee\xeb\x83K\xe3\xd4\xcb!"/\xef\xea\x10\xe5"\xecd\xe8N\xca\x83z+\x16v\xce\x9d4e\xa3\x12g5\xab1\x8bd\x7f$\x99\x1b\xc87f5\x14\xf9\xb9\xa4\xb3\x8b\xaa!&\xc4\x92N\xeb\x16HY\xf7c\x8f\xae\\\x14e\xa4\xfb\x8em\xf5\xebh\x8aNU\xb6}c\x97rM\xde>\xc4c\xeb\xb9]\xd0\xd2\xa9H\x85\xad\x93\xc4n\x18\x93|\xf8\xdc\x11K"\x12\xbb\xfb0\x07\x1f\x98r`\x9d\x804I\xe0\xb3\x1d1\x81:K\xb8\x99Fk\xa3\xfb\xc5#\xd1w.Yq\x9e\x0c\xffv"3\xeb\x07\xd3\x93H\xb4>\x18U\xbe\xd2\xa0T\xa0\xd2B\xd0\x808\xd7H\xecI_\xbb\x81,\xc43xvf\x8an:$Us\xe4n\xfa\x9c\x19\xad7\xa5A\xc0)\x14\x91Z\x02\xe6\x16\xddwR.\x81\xa3\x18(G\x08\x1b=$U\x8a\xc8\xd7\x03\x80\x93"\x18\xb2\xc2H\xb6\x95\xc0\x81\xafG\xc4E^\x00%\xb8\x19\xc5\xb9W\xf3cr}_\x0b7\xf9\x86\xea).\xa7\x90\xa2e\xeb\x85A\xb5+\x8d\x10\xc4v\xda\x17\xdf,a\x04aVv\xd2\xa9\xdc-J\x0b%\xa7\xd0\x15\xab\xdcC\xebr\xe2E\xb7\xeb5\x0b\xae\x11\xd6\xaa\x92\xa1B\x88\x066iY.\xb9i\\7(\x17dhU\xc2\xdfN\xddF\xd8\xe4\xf7\xd8\xcf\x07\xe0V\x93A\xd4o\x17uB\xc24h\xe5\xe7\xda\x9a\xed\x8d\xa9\xd0\x81\xb5\xa6-9\xd3\x1e\x86_\x03d\xe4\xd3\xc2\x9a\t\xfa]\x8cD\x9bH406\'4\xd0\xd7dl\x88\n\x0c\xb80\x04\x84Ug\xd5\xf2U-\x9c\xb4?\xe5\xb1J\xa6\xda\xa5\xff\x8bZ\xf1d\xf6P\x88\xa5r\xfeD\xb5U\x16\x83eK&\xc2z<bx7Tm\x82\xecy\x1a\x86lB\xbb\xc2Q\xa085l\x9bR\xfenZ\x15\xd6^\x90\xf6`U\x8b\xa6./\xbb\x99\x05\x10zIR\x01\xa3\\\xb4\xb5H`\'\xe3\xce\xee\xe6d\x81\x03\xcdR\xaf\xa8\xd6\xd0\x06\x92\xb6\x8a\x0b\x83h43\xc2\xccx\x1a\xf9\xc1%\xd3\xb6\xd6B\xa8\x82\xb1cl\xd008\x82\xd9\xde<\x80F#l\x00\xbbr\x91 \xb7\x97\xad\x83\xf8\x916\x03\x18Td\x18\x11\x83\x987\xcd\xe6\xd9+\x99\x8c\x02D\x0f\xc5\xc3\xab\xae\x10\x13\x1a>\x88\x89\xb2\x0c\x84\xc2\xa5\x02B\xfeJ\xa2F\\X\xb8K\x94\x00\xacr\'IR\x12\xc5\xb6\xfd\xd0\x00_\x80R\xd3\xebzf\x1825\xd1\x02/\x07\xf9\x18\x97"$K\xf8\xcc\x9cE!FH\x9c\x19\x960\x19\rk\x89\xda\x06\xc4\x94\xcbV\xcf\xdf#\xcb\xe8\xb2\xa7\xbd|s\xa5\xb9\xf5"~`\xf8\x1f\xbdx\xd3Z\x94\xa2*t;\xb0\x86s\xff\x89$X\xfd\xc0\xf7,R\x98\xc1OZw\xdc\xff`fP\x1f\xf4\xf6FM\xa6\x91\xd6]\x10\x15\xa1\xac\x93\xea\'\x97\xa6\xae\x9b\x8cN\x06O\xb0\xe8\x19Z#D\xb5\x17\xfdK\xa0\x7f\xa5\xa5\xef\x10\xa3+6ZQ\xbf]\x0c-;XU\x8b4\x99\xc3r\xda6\x03\x02\'Aa1\x9e \xf75j@\xce\xee\xd7\x1e6\xb6\x9bBfSMd\xac\xe1\xe8vLk4\xdf\x7f\xb9\xc3:+t\x8b]\xa9\xc5\x8e\xe4\xe5Y\x95\xab/\xecl\xf4\'\xa7\xa1\x9b\xed@\x84\x86\xabR\xa1X\x88\xe4\x9b[\x0bBT\x897\xbd\x85\xa9)\x1d-\xef\x82\x83F\xd2\xff!3\xb9\xc6\xc7\x00[m\xc6\x8d\xd1\tp\x05\xc0Q>\x8d\xed\xd6\xb2n\xc5\x17\xa0\x03g\x06\x1fR\x16\x96\x7f\x88\x82Ll\x88\xa8\x07\xc5\xdf\x9blwR\xd1\x83\xe5\xeb"R+\xc1\xb2\xb7$\x00\xfe\x00\x836\xa9*\x88\x19\xcd\x9e\x802\xc0\x90\xc4f\xa8\x06[\xb9\xf7\x9f\x0c\xa4\x97\xcf\xd7\xd7\xd0\xe9\x8b\x926\xaf\x0c\xdd{Eu\x8f\xd9\xc7b2\x0b@l\xd6T\xc2\x86\x13^9\x96k\x17\xdd\x19\xd3\n2\x17\xfa\x18,t\x05\x01\xd9\x85\xf8!\xa0\xcc\xd5yQ\n\x89\x00\x82K\t\x86\x8b\xe2\x97\x0b.\x9eSG\xaa\x9b<\xec,Cf\xd0R*\x9a`\x0ef\x92Y\x02[\x06\x0bc\xfa@\xa0\xedWv\xccLy\xa6\x93\x9f\x14\xb9x=\xce\xdac\x00\x9b\x0c(\x8b\xde\x19j\xcb\x0e\x1a]\xc9\xaf\x1c\xda\x10Q\xa9\x1d:\xbb\xd8\xdd\xd6\x88?L\x9d\xca+\x14\xb7bU3\xdd\\\x14ik\n\xc93\xa4$ZJ\x91\xddQ\xb7\x1e\xce\n\xc6\x8c%\xdb\x9b\xf9\x96\x0c\xa9\xae\x18\xd0\xa0\x11\xed\x1a5\xaaB\xbe\x06f\x81G\x83\xea(\x16\xb6\x88\x85%,\xa4H\x83O3r\x15Y\xbf\xc3\xb4p\x19\xfa\xef\n\xdbN\xb4=f\xbf\xad\x13\x00\xc0\x97\xde\xf2\xc4bbM\xd5\xc3Q\x9e%\x92 D\xe5\n\xf5*\x13\xf5`q\xd4P\xd5-\xd0\xfa[\x89\xbcZ\xa5\xa5kO\xd8\xb0)F\x90"\x01\x9b\xf0\'P\x88\x96\x9cM\xccW\x97K\xac\xc7*\xa0H\x97.{\xbcL\xea\x04#\xe5o\xe8g(\xd3\xf5\xeb\x0f\r+_a\xae\x98\xb7C\xc2\xbc\xe9\x1f\xe7\x8d\x8a\xe3dA\x08\x93[\xeb\x03~\xda;x\xd1c\x16f\xee\xb2\x96\x1d\xe6Yn\xa8-\xcbR\x8f\x8b\xa1\xb2\xce~\x85}(\xb9\x17>G\x0e\x801\x05F\x9ci\xf3\xdd\x96\xdb\xd2\xc0\x85\xdb\xa6R3T\x052\x16\x15\xb0\xa9"u\xe7\x1cx\xdf"E\xed\xd8\x17\xf9\xde\xc8\xfb#\x1a\xb1\xa6S\xb7\xc4\xebn\xd8_^\xda\x063\x86\xb28)S\t\x06jT\x14:\x87\x86<\xae\xb2\xf03,\x04E\xcfB\x82I,>\xab\xa5P\x91Z\r\x92\x9b\x82aW&N.h\xcc>\x7f\xe3\x07\xe0*@\xb3\xa2\x9e\x083\x9e\xec\xb8T(\xab6\xc5\xfa0\x1cI\xfb\xb2\x8c\xc1\xd2*\xd7.\xbb*\xd0\xac\xd8\x0c\xa9\xefT\x92\xc8\xb5\xc45\xc7.\xe6\xd9%6\xbe"\xb9r\xcc\x85.r\xed\x0e-\x17\xc4\xeb\x92\x99xQe\x8b\xe0\x01a1q\r0\x9fug\xd8P\xdf\'J/R\xb6\xb7\xec\xc1\xc5\xa7\xb4\xae\xe5\x193b\x84\x80f\xb1\n\x1b0\xc7\x1f\x86H.\xc2F\x97s\x00:\xee\xb3H4\xd9\x11\xa0\xe4\xbf\x0f7\x07\xc0%:rB<\xbd\xbbz\x9a\xf6\x13=\r\x88\xb3\x86\xf7\xc2MM!\xee\x17\xe9\xb6J\x99\x13\x1bM$\x84\x85\xea\x90\xb5\xeaC\x89\x12$Gsx\xe0\xc9\xf4\xc2U\xd5\x99\x94$\xb9i"\xb7\x0fQ\xbb,\x17\xa2P\xcc\xb7\x10g\xa5\xde\xa6\x11\xe4\x08m$Q\xedT\xf9\x91<\xc1=\x00I\x11\x83@\n\x98\xbf\x96\xa7\x8d\x9d\x1c\x80SC\xa40%"R\'\xd1F\xdb\xc8\x88\xeaJ\xab\xd1\x1eQ\x89\x88\xaa\x99\xaf\x1e\x15\x90Q\xc6G\xc4\xda\xe6\x94I\x11\xe1\x84\xda\x12r[\x11U\'$\x82\xa3\xb8#%\xf7Ki\xf7v\xc7\x00\xf4\x06\x15\x1a)v&G\xe2u\x8b\x94.R\xd4\x16\x89e\xe5\xd6\xaa\xff\x81\xda\xb1\xdb\xc2\xba\xadz\xd0Wn\x1cW\x91\xef\xdc\xda\xa3\xc4Q\xa8\xec\x00\x03\x91\xf9\x08E:\xb3X\xbf<\x17W\x0c\xd2-\xa6\xedp\xda\x14\x0c(r\xd3f\x9fs\x8aT\xa94\x8aB\xc1o$\x85\xcc\xf3\xec\xcf\xa5\xc1>\x9a\xaa\x90\xec\xdf~\x04p\x81\xf98ia\xadS\xef/o5\x8f\x04NI\x11\xcd]\x90\xbe\x8b-#\x8b\xf9F8w\x15\xfb5\xeeD\xae\x8f\xd1* jy\xa6y\xf1\xa0\xcd\x8b/0K\x93\xe5\x96x\x00<z\xb9\x83\x8c\xab\x0bv\xda\x8e\xb7\xb4\xa1\xe7/\xb5e\x90\xe4Y\xf7\xca#\xcc&\xd3\xda\xf5\x9f;\xc0\xca\n!\x11\xd9e\x1a\x1f\xf2\x14\'\x0e\t\xd7\x13\xdf\x12|X3q\xd6^\xc6\x8ba\x83\x1c\n>\x86dz:\x18n\x9b\\b\x16\xe4EQ\xb5a\x9f9\xea\xd9\x8a\x16\x91\x80\x99\x96\xb6jz\xa8"\xe2TG\x05*\xcf\xc2w4\xdd\x88\x93#\xef^\xb7\xf7l\x1b@#3\xcd\xe4l\xd0+*\x17\xd7\x04\xb0\xcd(Vpf\x92F\xa8?Z\x88\xa9\x16\x80\xe1a\xd8\n14<z\x85\xb8\xdci\x0c\x81\xac-\xc4\x82P!\xd5Z\xc0k2C(\xe7=\xf6\xb1\xb0\x9d\x0e\x86p@.\xaa\xe9\x07\x05\xdb\xf6V\x1d\xffj$\xf2H\xe7\xd6[\xd4\x8b4&_&f\'\xbbb<\xfd{\xd0H8/\xd7\xbb\xf7\xc5Uryz@cdh\xa1P60u\x9b@s\x9b\x9b\x00)\xa9\x8a>\xef:G\xf2Rn\xd4\x18l@\x92\x8a\x18\x19B\xb5eRG\xc6\x90\x88\xe6EYt_\x97\x07\xeft\x05UYm\xef\xa1\xd8l\xdaV\x08\xe4\x96\xf0\x8e\x1b\xb5P\xd9\x8eqw\x11Yqa\xd2]\x95\xe3\x1d\x12\x8a2\x87\xd7<\xfa\xd8\x91|D\xf9\xa0\xa94+vV]OU\xfe0n\x83\x1e\x14d\xb5\xdd\xcc\x88\x87]]\x9f\x14\x94T\x96\xf7\xdc\xea\xfb\x03\xb4\xf8y\xaf\xd4\xfc\x08\xbc\x1bA\x1eS\x95\rL\x8d\x8f6\x96\xbaYD\x13I\xf0\xec\x97\xa3%X\xbf\xa2icy\x15*1\xfcA\xe4\xb3\xae\xeeMa;Q\'\x97\\\xea\x95\xf8j{\xfb\xe2P,5=\x98\xd6]\x83\x9b\x89\xce\x8f\xe6\x8aS\xf6f\x07Y_J3\x07K\x0f\n\xe25\xbd\xfd8\xe0\xa4\xeclQ\r\xffV\xd1X5\x11\x8aL\x15\x94 e\x90;\x9eQ2\xde\xdc@\xefv\x8c\x8a\x82;\xb2\x14D\xf1\x00\xf0%FNA*T.@T\xa4)R^\xcf\x9b\x85\x7f\x0cF\xa5;\x0e\x16\xfam\xa7)fV\x80\x15Qr(\xa0\x88\x85\x8d:~\xf3\xa6j[zY\xeezK 7h\x19!\x01\x0e\xc9j\xdf\xb2\x13\x02\xf1 \x01\x98\xb7f\xd4S\\n\xc4\x8e\xd9e\xf0*\xde"_\x0e\xf5cWR\xbb\xaa*\x06Z\xa5\xf2W\x82\xa4\x1ea<\x11\xa4Tj\x08\xf5\xa4|\xe6p\xfd\xcd\x88\x13\x1f\xfe\xb15\x89\x00\xbc\x88\xf2\x96\x8cv{\xcbmvT6-3\x03\xcc*%\xc4\xbb\x8bzmU;\xb2\xae]J~\x7f\x90ir"0E\xcc\xb2\xdcv\xc5\xfe\xb8\'\\>\xa9\xcb#\xf2\xda\xc5\xa1s\xee\x88n\x01R\x08\x85\xa6\x9d\xe0\xa5\x8b\xc5]\x14\xdb\xd4\x06\x84\xbc.\x88\xa5{\x94h\xa0f\x0f\xbbEa\xf9\n\x850\xf1}\xbb\x88\xda+\xe9\x8f\x118\xd4\xc4\rj3\'\xcb\xac\xd3\xc1\x1f \xf9\xa3*\xa3\xebWYn\x9a\x19c\x1c\x9b\x87\xa5<!]\x99\xb1\xe9\xb7D\x1a\x8c\x12\xcd}9(\'\xb1\x1b\t5\x82\x0b\xb4g\x8c_\xcbZ\x9d)\x01\x033\x15\x98\xc9\x995g\x81I\xa3\x1bL\x98\xa3\'&\xabA\x8e\x0b\x03F\xe7\x10\xa4\x82:\x07\xeegC"\x99\xc1&\xed--\xc80%\x0cw\xc3r\xc1@\xbf5\xe8!\xa6-\xed\xc3\x9d\xa5T\xe2#\t\xa8\xc3\x15\x92%\x04U\x9d\xbe\x0b\xd6gq\xf2ry\x1e\x92\xda\x15;\xb1\xde\x97\xba\x9c\xfc\x8a\xf4 dM\xfe2\xd8\xdb\x91\x1feF#v\xe2b\xafk\x8bU$\xe9\rl%\x16Ct!\x16zI\xcfu2of\x8d\xe3\x01\x816\x93\xcc\xac\xa1\xd4\x8f\xea8\xddg\xa6@\x9b\xc1\xa8\xb7\x93\xc5*\xd9\xd0\x98\xed5@ed \x8bl"\x92\xb6Y>\xfc\xab\xb1\xb5\xb9\xc00\x92^\x00\x1d\xfd\xc3\x7f[\xb5F\x0f\x95\xc9\x8a\xb0\xea\xe3)\xa4\x1f\x84\x9e.<t\'\xbf\xd2\xe27\xf2\x12\xaf\xdal1F*sEs\xdc\xcc\x9e(\xcd\x12\xa9\xcf\xfbw\xa4.-<P\x04\xda\x80\xd4\x9b\tD\x06\xceX\xdf\xcc\xd2FG\t\x15QH\xacvhZ\xf1\x10K\xc8\x91\x18Z0\xa0\x1e\x8a\xfe\x97&4\xee\xe9m\\Q\xa9\xd2\xcdt\x9c\xd9xQ\x01k\x0fak\xa8\x17PY\xd5\x8e\xa5)\xca\\\\\xdep\xd8l%n_\xaa\xae\xd0\xaa\x8a\x96\x9eT!G\xfd\xa51\xcb\x9e\x14^\xd0=X\xb9n\xb7\x92I\xacI\xf1\x9f\xb6\xe4\xd2n\xb5H%\xa5\x9b\xce\xc7d\xed\xb2\xc8\xca\xe6\x07\x18h\xbb\xdd\x15\x94_\x83=\xf1\x00\x02\x13\xfddO\xaa\xf5\xe64{\xfb\xb5>\x9a\x00:\x11Tp\x91\x04f\xd6\xbc\xcd\x9exh\xc4\xf6\xb8(\x8ed\x16\xbd\xa8]\xf6\x12\x1d\xa5\x85\x1c\xd4(\x15\x99\xd0\x086\x98\xdd\xe0\xbf\xe4\xfa\x9db\xdfz{U\xaf"\xda\xa2\xc1\xef\x16F\x8d\xae\xfd\x89\xb6[q\xc5v\x9br\xc9j\xfc\xde\xfd\xca:\x1e\xb2\xea-\x94Lmb\xf9\xc2\xd7 6\x06Yt\xf6w\x93\xcbD\xae\x069OQGa\xb2}\x04\x96U}\xe0\x89\x07\x93\xa43\xee\xf9\xda\xfe!C\xaa-R\xd1qq1\x92\xc3%\xc1J\xd3v\xe2\xbc{w\x9a\xe2\xbb\x89\x0f\xe96-,\xe7\x8d2\x8dc\\\xa3Re\xdf\xe4C-\xf4\x16!\x97\xc0er7\x88\x9b\xea\x92\xe4\xcc`!\x94G\x91\x8a\x8a\xa4"\x07\x8e\xed\x90\x84Y\xa7\x98\xaabB\xb6\xc7\'i.\x92\x93\xefi*\xe0\xeb\xad\x9f\xd1\xaf\x0e\xa4#\x0e\x88\xe0\n\x03\xc3N\xdaE\x17\x85[\xf6yT\xbbEvm\xc0erQ\xd4 \x0c\xe5yK\x7fnK_U\xaaUH\xb7"\xb0\xee\xbe\xa1\xd3\xee\xc8\x1c \xf1\xccn\x95/\xc5\xccJ\x8e\x8ah\xa6kE\xb9G}\xc1,\x1c\x1a\xf0U\xb7\x80\x0e\x88\x13`\xe2\xde.-\xfd\xc0\\\xbe\xa9\xc6\x0f\x7f\xe21\x15V5q\xa0"\x0b\xc48u\x06\xd3\x91nn9\xc0>\x92\xea5\xdc\xb5"\xcd;Y\x8d\xa87\xb9\x98\x9fH\xc4\xa9\xe5\xa8Z2+Q\xb1\xb7\xedHL&%1\x8f]\xea%ovSG_&\x1b>?g\x05\xae\x88@F\x95H"\ntW\xa7\xc4~\xf5\xa5\xf74\x06h\xc0\xe4a%\x8a\xbdA_\x13\x11B\x9aK\xban\xf6\x81\xa0%\xc2 #\nO\x99\x05:vFP\x1e\xc7`=\x93\xc0=\xf3-\xed\x19]HcZ\x96\x95#\xfc\xdb\xca\xc17\xa4\x98^\xf7\xcb\xf3\x0e\x8b\x1d4C5\xc7\xea\x0e\xf8\x1e\xa3\x96\x9a\xed\n\xb4\xc3J\xc9>\xa1\xd6\xa8\xe1\x9bp\xc4\xe1\x07\x90\xcc\xf6\xbe\xd7\xd5\xb0\xc7\x1d\x11\x90\xaf\xfa\x0e+\r\xef#W\xa8n8\xca\x8exS\x15\x02\n\xddd\xcdR@\x1axo`O!+\xc6y\xab\xabQ\xa0\xf0\\o\xea-\xe1\x88\xa0,C\xd9N!k$\x98\xecuZ\xb7\xa9\xa15S\xadD\xbe\xb4"\xc5t\xe5e\xbfy\xfdb\xb6T\x98S{\xb7\x99\xccy\xd1\x97\x00_\xdc\xdf\x15\xcfr\xfb\xef\x121\xcb\xb1^\x1cp\xd4\x8b\x89p\xbf\xc1\x12c\xe9\xc4\x02\xa6\xd7j\xfa\xb7\x7fF\xc7B\xc3\nZ\xe4\xae\x1f|f\xd6@e\x9e.\x13\xd4\xa0H\xb14\xfaM*\xa94\xd5\x87Lw\xa0\xc5\xa2\x1a\xf9\xf6\x17\xd3\xdc \xcb[\x8fC\xbc\xa7r\x89\xad\xb0\x1d\x97(k\x16\x80\xe7N7\xb40*\xeeh\x14\xe3\x8b\xc7\xb2-\x16k\xcc\xdd\xf2O\x8bD)\xablC\x9b:\xe3no\x06|\xb58:\xc9\x0cig(\x0b\xb9!\x8biy\xd2\x91!\xe5OoC\xdf\xf0\x88\xa2\x14\xea\x9e}\x8aiQ)m\x1fu.\x17#+\xb7\xcc\xe5=\xf4G\xf6\xfe\xe1\x9e\x127\xd1\t\xb0\xdf\xb2@\x18:\x14\xebDe)G\xda\x0b\xe1\xfb\xca\x02\xcd\xad?)\xb2\xde2\xc2{\x91W\r\xd5\xba\xf9<\x02\xb3\x80w\x92\xd7\x11\x96\xe7\x0e\rg\xd6(\x8c3\xfb\x11\xf1\xe2s#_vu0\xc1g\xa2\xe9.\xfa\xb8\xab)\x8e\x80us\xb1v\xba\xd0\x98\xc392\xf5A\xf5\xc7\x83s\xfa\xe0\xd2\xb8\r\x05<"\xd6y]\xab\xca\x84y\x84d\xacp\x17z7\x9e\xdd\xd4\xb8\x95\xc8t\xbc \xf9\xb9\x90_P\xa6\x8dLD\xc6\x8f\x10\xa6\x83\xa5\xd8\x10\x1e\x850~\x08;\x15\xc3\xb5\x9c6\xfb\xc2K\x86\x0e\xadH/A\xd2\xabe\x1fU\xdf\x82\xba\xf5\xc0\xb5\xaa\x9eX\xd9f\xba\xd5\x9d"$\x14\xac5\xe2\x0b\xd2\xcdA\xde\xc8\r\x99\xd9\xe7\xab\'\xad;\x94\xcfymT\x85A\xf5\xec\xbb\x1b1<#\xf6r0\t\x80\xde\xf7\xa0dc\xc8Gw\xc7\xb0\x11\x8f\x15\n\xb8 E\xcaf\xa4\xaaE\r1\x95\xdbf\x08\xa8)\xa8\xca`\xa4\xfdp\xab\x15\xaa\xe7\x0e\x1d\x98\x83r\x9c\xea\xe5\xd5\xa3\xcam\xd6\x8b\xaaC\xcfw\xc1$\xe7\xe8D\xa9\xd1\xb2\xb5W2\x99*\xa4\xe8\x10\xd1\xab\x05\xd9x\xadx\xa0@\xcb\x81*9\xbf\xc7\xc5\x92\x88!\x83{^W\xf5o\xbb~\x00[\xbe\xcd\xdbn\x90\x0e\xe8\x90\x985\xbc\x99#\x14\xc6\xf9\t\x8bi~\xa8\x1a\x84\xd4\x15\xd0F\x19o\xb0^\x80\xe8*\xc4\xdd9\xb0a\xc0\xcc\x1c=\xf5\xe0\x9e\xe2\xe3\x01\x195@\x1dH\xc0\x9f.\x9f\xdeE\x13f]# \xebK/+\xc4R\xbc`\xcc\xf5\x96cp\xc8}\xden\xd6,0\x05\x8eL\xcf\xa7D\x97=\x19\xa5\xd6s\xdd3%J3\xb7\x14\xe2\xce\xc2q\xb8\xac\x04\xb6%2M\xcd\x97\x95U\xd7\xe7FT\x89\xf0\x04\x96Y@\xbeu\xda\x91y\x13\xe1\x91A\x83\x11eE\x19I\x92\xc9*\xdd\xc7\x97\xd9\xda\xb4\x192\xd8\xb7"}\xbe\x87\xe0\x92M\xddT\xd7WQaD}\x13\xc9\xad"\x15\xbc\x99]\x80\x0c*\xa5:\xc5F\x0e\xc8\xfdD\xa2\x96\xa6\x9a\xb3\x0e\xbd;\xbe\xda#\xd1\xa8\xd9\x19<\xa0\xc4=P\xaf\xba\xa9\xe6+\x8a\x9bP\x08\xdc\xc7\xd8>\xb8\x10\xb2$,\xad\xd8\x86\xaa\x8f\x97Z\xca\x9eECn\t\xee\x1e\x9c%\x06\x0c\xa55\tF\xaa|\xe0\x9e\x82\x92\x87:C\x0bj\xd9\xa6\xe1\x8dK3X\xe2\x86\x7f9\xf9+\xc5[\x9bC\xf8\xad\xa4\xb7Q\xf3\x07\x16qj\xf3y\x1b\xa4X2v\x81\r\x8a\xd5\xbc\xbe*R\x9d\xa2tY\xf22\x80.\xce:\n\xd3\x1e[\x9d\x0e\xb9\xe8\x14JT7\xc4N%\xbd\x80\xb8\xf9\xa0sv\xfb$\x9f-\xf4\xad\xd6l\x87\xe8\x80\x03fuY/N\x9c\x03P\x97\x0f\x7f\x17\xd8e\xb6\xeeq\x8b\x18\x8f\x8fI\xb7g\xce\x08\xb8\xedv\xed\x0cR\x11\xc22\x82\xbcWeG\xc7.S\xb0u=\x91\xb6\x9e\x82r\x17\xe4t\x9d\xb2&z)D\x91f[oul\x87`\xc5:\x15\xdf\x9c\x03\x1c\x87[\xbb\xe0X\xc5\xb6\x8cc)\xf2\xe3&BQH\x83\x0b\x8d\x81\xf4\xaf\x86-\xc1\x97\xb3\x0b\xe9\x04\x1a\xcb\xc9)j{\xa4~\xf3\x0e\x9d\x0c\xec=\xe4\x84\x88\xfe\x1e`\xbc\x18v\xc3n\xf61A\x99\x12\xdd(bjAn\x84%s*\xdf\xde\xb6O\xcf\x9bB\x1cGV\xeb\xdd\xcf\xb5_SD\xb6\xd1\xf8A\x0e\x90\x8d\xee\xa4\xf95\xf3\xb4\xd4 \xcdab\xa3\xbeV\x0e{\x00\x93\xbam7V\x9a\xc6\x8e\x967do\xf5\xeah\xea\xca\x01\xb3\x1c\xbeU6L\xd5\xc7\x03\xefJ\x82eK:\xcf\xc2N-K\xa3uf?z\x84\xfe\xafT\x86cN#\xd2\xaf\xc2\xfd8K.6\xedV\xa8\xbe\x9d/;p\xda\x8a\x97\x97\xcc\xe6\xbf\xe4{\x04\x96\xa1#\xe4\x91m\xdf\xcel\xc6\xc3\x9c\xb5_\xdc\x8f\x0bS\x8b\x0b\x1e\xfd\xc5\x

In [35]:
import zipfile
import os

# Unzip the file
with zipfile.ZipFile('ht.zip', 'r') as zip_ref:
    zip_ref.extractall('.')

print("File 'ht.zip' unzipped successfully.")

File 'ht.zip' unzipped successfully.

In [36]:
# List the contents of the current directory to see the extracted files
%ls -F

 diabetes.csv   ht.zip   sample_data/
'ht (1).zip'    mydir/   untitled_project/

In [37]:
import pandas as pd

df = pd.read_csv('diabetes.csv')
display(df.head())

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [38]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [39]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [40]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=scaler.fit_transform(X)

In [41]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [42]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [43]:
model=Sequential()
model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [44]:
model.fit(X_train,y_train,batch_size=32,epochs=100,validation_data=(X_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 4s 32ms/step - accuracy: 0.6482 - loss: 0.6588 - val_accuracy: 0.6688 - val_loss: 0.6269
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7362 - loss: 0.6044 - val_accuracy: 0.7143 - val_loss: 0.5893
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7671 - loss: 0.5666 - val_accuracy: 0.7403 - val_loss: 0.5637
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7638 - loss: 0.5382 - val_accuracy: 0.7468 - val_loss: 0.5450
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7687 - loss: 0.5170 - val_accuracy: 0.7597 - val_loss: 0.5317
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7736 - loss: 0.5013 - val_accuracy: 0.7662 - val_loss: 0.5206
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7769 - loss: 0.4892 - val_accuracy: 0.7727 - val_loss: 0.5143
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.7834 - loss: 0.4809 - val_accuracy: 0.7727 - val_loss: 0.5096
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7785 - loss: 0.4735 - val_accuracy: 0.7597 - val_loss: 0.5062
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4671 - val_accuracy: 0.7597 - val_loss: 0.5050
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4631 - val_accuracy: 0.7532 - val_loss: 0.5039
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4590 - val_accuracy: 0.7727 - val_loss: 0.5033
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4556 - val_accuracy: 0.7597 - val_loss: 0.5033
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4531 - val_accuracy: 0.7597 - val_loss: 0.5050
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4502 - val_accuracy: 0.7597 - val_loss: 0.5059
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4479 - val_accuracy: 0.7597 - val_loss: 0.5054
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4460 - val_accuracy: 0.7597 - val_loss: 0.5080
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4440 - val_accuracy: 0.7532 - val_loss: 0.5067
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4423 - val_accuracy: 0.7532 - val_loss: 0.5073
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4409 - val_accuracy: 0.7597 - val_loss: 0.5074
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4397 - val_accuracy: 0.7597 - val_loss: 0.5084
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4377 - val_accuracy: 0.7468 - val_loss: 0.5099
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7932 - loss: 0.4370 - val_accuracy: 0.7468 - val_loss: 0.5123
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7932 - loss: 0.4357 - val_accuracy: 0.7532 - val_loss: 0.5125
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7932 - loss: 0.4345 - val_accuracy: 0.7532 - val_loss: 0.5151
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7964 - loss: 0.4337 - val_accuracy: 0.7468 - val_loss: 0.5156
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7980 - loss: 0.4331 - val_accuracy: 0.7662 - val_loss: 0.5150
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7948 - loss: 0.4318 - val_accuracy: 0.7662 - val_loss: 0.5145
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7932 - loss: 0.4306 - val_accuracy: 0.7662 - val_loss: 0.5141
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7932 - loss: 0.4296 - val_accuracy: 0.7662 - val_loss: 0.5158
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.7932 - loss: 0.4298 - val_accuracy: 0.7597 - val_loss: 0.5166
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7948 - loss: 0.4285 - val_accuracy: 0.7532 - val_loss: 0.5175
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - accuracy: 0.7980 - loss: 0.4276 - val_accuracy: 0.7468 - val_loss: 0.5203
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.7948 - loss: 0.4273 - val_accuracy: 0.7468 - val_loss: 0.5207
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.7932 - loss: 0.4264 - val_accuracy: 0.7468 - val_loss: 0.5217
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7980 - loss: 0.4252 - val_accuracy: 0.7597 - val_loss: 0.5215
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7948 - loss: 0.4250 - val_accuracy: 0.7597 - val_loss: 0.5222
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7915 - loss: 0.4243 - val_accuracy: 0.7532 - val_loss: 0.5234
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7948 - loss: 0.4233 - val_accuracy: 0.7532 - val_loss: 0.5210
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.7997 - loss: 0.4229 - val_accuracy: 0.7597 - val_loss: 0.5214
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7948 - loss: 0.4227 - val_accuracy: 0.7597 - val_loss: 0.5215
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8013 - loss: 0.4220 - val_accuracy: 0.7597 - val_loss: 0.5216
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4210 - val_accuracy: 0.7597 - val_loss: 0.5229
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4207 - val_accuracy: 0.7727 - val_loss: 0.5240
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4199 - val_accuracy: 0.7662 - val_loss: 0.5251
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4193 - val_accuracy: 0.7597 - val_loss: 0.5254
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4186 - val_accuracy: 0.7532 - val_loss: 0.5267
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4178 - val_accuracy: 0.7597 - val_loss: 0.5249
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4176 - val_accuracy: 0.7662 - val_loss: 0.5261
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4167 - val_accuracy: 0.7597 - val_loss: 0.5271
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4165 - val_accuracy: 0.7727 - val_loss: 0.5268
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4158 - val_accuracy: 0.7468 - val_loss: 0.5280
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4153 - val_accuracy: 0.7532 - val_loss: 0.5278
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4147 - val_accuracy: 0.7597 - val_loss: 0.5283
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4142 - val_accuracy: 0.7532 - val_loss: 0.5304
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4135 - val_accuracy: 0.7532 - val_loss: 0.5313
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4134 - val_accuracy: 0.7532 - val_loss: 0.5302
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4125 - val_accuracy: 0.7532 - val_loss: 0.5307
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4122 - val_accuracy: 0.7532 - val_loss: 0.5309
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4120 - val_accuracy: 0.7532 - val_loss: 0.5322
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4113 - val_accuracy: 0.7468 - val_loss: 0.5325
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4107 - val_accuracy: 0.7468 - val_loss: 0.5325
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4105 - val_accuracy: 0.7532 - val_loss: 0.5340
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4098 - val_accuracy: 0.7597 - val_loss: 0.5339
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4096 - val_accuracy: 0.7597 - val_loss: 0.5331
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4090 - val_accuracy: 0.7468 - val_loss: 0.5342
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4086 - val_accuracy: 0.7532 - val_loss: 0.5325
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4085 - val_accuracy: 0.7532 - val_loss: 0.5335
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4086 - val_accuracy: 0.7468 - val_loss: 0.5347
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4071 - val_accuracy: 0.7532 - val_loss: 0.5343
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4072 - val_accuracy: 0.7532 - val_loss: 0.5365
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4066 - val_accuracy: 0.7532 - val_loss: 0.5370
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4063 - val_accuracy: 0.7532 - val_loss: 0.5360
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4063 - val_accuracy: 0.7532 - val_loss: 0.5368
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4054 - val_accuracy: 0.7532 - val_loss: 0.5367
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4046 - val_accuracy: 0.7532 - val_loss: 0.5355
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4052 - val_accuracy: 0.7532 - val_loss: 0.5336
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4042 - val_accuracy: 0.7532 - val_loss: 0.5353
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4036 - val_accuracy: 0.7532 - val_loss: 0.5370
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4034 - val_accuracy: 0.7532 - val_loss: 0.5388
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4034 - val_accuracy: 0.7532 - val_loss: 0.5378
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4034 - val_accuracy: 0.7468 - val_loss: 0.5394
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4022 - val_accuracy: 0.7468 - val_loss: 0.5390
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4025 - val_accuracy: 0.7468 - val_loss: 0.5389
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.4025 - val_accuracy: 0.7403 - val_loss: 0.5403
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8078 - loss: 0.4019 - val_accuracy: 0.7403 - val_loss: 0.5414
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8078 - loss: 0.4015 - val_accuracy: 0.7468 - val_loss: 0.5401
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8094 - loss: 0.4012 - val_accuracy: 0.7403 - val_loss: 0.5402
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8094 - loss: 0.4005 - val_accuracy: 0.7403 - val_loss: 0.5414
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8046 - loss: 0.4001 - val_accuracy: 0.7403 - val_loss: 0.5425
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8111 - loss: 0.4002 - val_accuracy: 0.7403 - val_loss: 0.5411
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8094 - loss: 0.3996 - val_accuracy: 0.7403 - val_loss: 0.5405
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8111 - loss: 0.3989 - val_accuracy: 0.7468 - val_loss: 0.5425
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8062 - loss: 0.3992 - val_accuracy: 0.7468 - val_loss: 0.5449
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8062 - loss: 0.3989 - val_accuracy: 0.7468 - val_loss: 0.5451
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8078 - loss: 0.3983 - val_accuracy: 0.7532 - val_loss: 0.5449
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.8094 - loss: 0.3987 - val_accuracy: 0.7468 - val_loss: 0.5430
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8094 - loss: 0.3980 - val_accuracy: 0.7468 - val_loss: 0.5451
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8111 - loss: 0.3972 - val_accuracy: 0.7468 - val_loss: 0.5448
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8094 - loss: 0.3967 - val_accuracy: 0.7468 - val_loss: 0.5438

In [45]:
pip install -U keras-tuner

Requirement already satisfied: keras-tuner in /usr/local/lib/python3.12/dist-packages (1.4.8)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.81.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.5.20)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)

In [46]:
import kerastuner as kt

In [47]:
def build_model(hp):
  model=Sequential()
  model.add(Dense(32,activation='relu',input_dim=8))
  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer=hp.Choice('optimizer',values=['adam','sgd']),loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [48]:
tuner=kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5)

Reloading Tuner from ./untitled_project/tuner0.json

In [49]:
tuner.search(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test))

In [50]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [51]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [52]:
model.fit(X_train,y_train,batch_size=32,epochs=100,validation_data=(X_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7720 - loss: 0.4967 - val_accuracy: 0.7792 - val_loss: 0.5066
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4857 - val_accuracy: 0.7792 - val_loss: 0.5018
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4774 - val_accuracy: 0.7727 - val_loss: 0.5002
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4713 - val_accuracy: 0.7662 - val_loss: 0.4979
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7671 - loss: 0.4649 - val_accuracy: 0.7662 - val_loss: 0.4959
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7671 - loss: 0.4602 - val_accuracy: 0.7662 - val_loss: 0.4967
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4560 - val_accuracy: 0.7532 - val_loss: 0.4979
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4524 - val_accuracy: 0.7597 - val_loss: 0.4981
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4498 - val_accuracy: 0.7597 - val_loss: 0.5002
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7801 - loss: 0.4472 - val_accuracy: 0.7532 - val_loss: 0.5007
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7769 - loss: 0.4452 - val_accuracy: 0.7597 - val_loss: 0.5032
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4435 - val_accuracy: 0.7532 - val_loss: 0.5026
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4416 - val_accuracy: 0.7597 - val_loss: 0.5039
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4400 - val_accuracy: 0.7532 - val_loss: 0.5049
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4388 - val_accuracy: 0.7532 - val_loss: 0.5053
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.4377 - val_accuracy: 0.7532 - val_loss: 0.5060
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7785 - loss: 0.4366 - val_accuracy: 0.7532 - val_loss: 0.5070
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7818 - loss: 0.4356 - val_accuracy: 0.7468 - val_loss: 0.5084
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7850 - loss: 0.4354 - val_accuracy: 0.7532 - val_loss: 0.5098
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7834 - loss: 0.4336 - val_accuracy: 0.7468 - val_loss: 0.5092
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.7818 - loss: 0.4330 - val_accuracy: 0.7468 - val_loss: 0.5114
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.7785 - loss: 0.4318 - val_accuracy: 0.7468 - val_loss: 0.5126
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.7834 - loss: 0.4315 - val_accuracy: 0.7532 - val_loss: 0.5105
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7834 - loss: 0.4306 - val_accuracy: 0.7468 - val_loss: 0.5099
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.7883 - loss: 0.4300 - val_accuracy: 0.7532 - val_loss: 0.5093
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7785 - loss: 0.4287 - val_accuracy: 0.7532 - val_loss: 0.5125
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7801 - loss: 0.4281 - val_accuracy: 0.7532 - val_loss: 0.5161
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7834 - loss: 0.4277 - val_accuracy: 0.7532 - val_loss: 0.5155
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7850 - loss: 0.4268 - val_accuracy: 0.7532 - val_loss: 0.5157
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7818 - loss: 0.4263 - val_accuracy: 0.7532 - val_loss: 0.5156
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7866 - loss: 0.4254 - val_accuracy: 0.7532 - val_loss: 0.5183
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7948 - loss: 0.4249 - val_accuracy: 0.7468 - val_loss: 0.5191
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7948 - loss: 0.4246 - val_accuracy: 0.7532 - val_loss: 0.5170
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7866 - loss: 0.4241 - val_accuracy: 0.7532 - val_loss: 0.5160
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7866 - loss: 0.4233 - val_accuracy: 0.7532 - val_loss: 0.5157
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7883 - loss: 0.4227 - val_accuracy: 0.7532 - val_loss: 0.5181
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7850 - loss: 0.4225 - val_accuracy: 0.7532 - val_loss: 0.5180
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7899 - loss: 0.4218 - val_accuracy: 0.7532 - val_loss: 0.5183
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7932 - loss: 0.4213 - val_accuracy: 0.7532 - val_loss: 0.5204
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.7899 - loss: 0.4208 - val_accuracy: 0.7532 - val_loss: 0.5184
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7915 - loss: 0.4202 - val_accuracy: 0.7532 - val_loss: 0.5181
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7899 - loss: 0.4197 - val_accuracy: 0.7532 - val_loss: 0.5176
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7834 - loss: 0.4195 - val_accuracy: 0.7532 - val_loss: 0.5209
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7866 - loss: 0.4188 - val_accuracy: 0.7532 - val_loss: 0.5211
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7915 - loss: 0.4184 - val_accuracy: 0.7532 - val_loss: 0.5237
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7915 - loss: 0.4176 - val_accuracy: 0.7532 - val_loss: 0.5242
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7899 - loss: 0.4175 - val_accuracy: 0.7403 - val_loss: 0.5235
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7932 - loss: 0.4168 - val_accuracy: 0.7403 - val_loss: 0.5243
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7932 - loss: 0.4166 - val_accuracy: 0.7468 - val_loss: 0.5219
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4161 - val_accuracy: 0.7468 - val_loss: 0.5215
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4154 - val_accuracy: 0.7468 - val_loss: 0.5233
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7964 - loss: 0.4150 - val_accuracy: 0.7468 - val_loss: 0.5253
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4146 - val_accuracy: 0.7532 - val_loss: 0.5234
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4138 - val_accuracy: 0.7468 - val_loss: 0.5232
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4136 - val_accuracy: 0.7468 - val_loss: 0.5226
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4136 - val_accuracy: 0.7468 - val_loss: 0.5229
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7964 - loss: 0.4127 - val_accuracy: 0.7597 - val_loss: 0.5225
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4122 - val_accuracy: 0.7532 - val_loss: 0.5235
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7883 - loss: 0.4122 - val_accuracy: 0.7532 - val_loss: 0.5229
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4117 - val_accuracy: 0.7532 - val_loss: 0.5246
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7980 - loss: 0.4109 - val_accuracy: 0.7597 - val_loss: 0.5231
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4110 - val_accuracy: 0.7662 - val_loss: 0.5223
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4101 - val_accuracy: 0.7597 - val_loss: 0.5239
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4104 - val_accuracy: 0.7403 - val_loss: 0.5264
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4094 - val_accuracy: 0.7468 - val_loss: 0.5288
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4091 - val_accuracy: 0.7468 - val_loss: 0.5276
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4082 - val_accuracy: 0.7468 - val_loss: 0.5291
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4078 - val_accuracy: 0.7403 - val_loss: 0.5315
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4075 - val_accuracy: 0.7468 - val_loss: 0.5314
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4070 - val_accuracy: 0.7532 - val_loss: 0.5288
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4067 - val_accuracy: 0.7597 - val_loss: 0.5251
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4061 - val_accuracy: 0.7532 - val_loss: 0.5274
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4055 - val_accuracy: 0.7532 - val_loss: 0.5282
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4058 - val_accuracy: 0.7597 - val_loss: 0.5276
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4047 - val_accuracy: 0.7597 - val_loss: 0.5283
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4045 - val_accuracy: 0.7532 - val_loss: 0.5274
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4040 - val_accuracy: 0.7532 - val_loss: 0.5291
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4036 - val_accuracy: 0.7597 - val_loss: 0.5316
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4032 - val_accuracy: 0.7338 - val_loss: 0.5364
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4028 - val_accuracy: 0.7468 - val_loss: 0.5341
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4028 - val_accuracy: 0.7403 - val_loss: 0.5354
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8062 - loss: 0.4023 - val_accuracy: 0.7532 - val_loss: 0.5327
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4016 - val_accuracy: 0.7532 - val_loss: 0.5332
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4013 - val_accuracy: 0.7532 - val_loss: 0.5346
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4006 - val_accuracy: 0.7468 - val_loss: 0.5355
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4008 - val_accuracy: 0.7468 - val_loss: 0.5364
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.3995 - val_accuracy: 0.7468 - val_loss: 0.5353
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.3998 - val_accuracy: 0.7532 - val_loss: 0.5343
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.3990 - val_accuracy: 0.7468 - val_loss: 0.5343
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.3989 - val_accuracy: 0.7468 - val_loss: 0.5349
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.3993 - val_accuracy: 0.7468 - val_loss: 0.5345
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.3986 - val_accuracy: 0.7468 - val_loss: 0.5336
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.3979 - val_accuracy: 0.7468 - val_loss: 0.5336
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.3975 - val_accuracy: 0.7468 - val_loss: 0.5339
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.3972 - val_accuracy: 0.7468 - val_loss: 0.5359
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.3965 - val_accuracy: 0.7532 - val_loss: 0.5356
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.3964 - val_accuracy: 0.7468 - val_loss: 0.5353
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.3960 - val_accuracy: 0.7468 - val_loss: 0.5355
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.3966 - val_accuracy: 0.7532 - val_loss: 0.5346
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.3961 - val_accuracy: 0.7532 - val_loss: 0.5369

In [53]:
def build_model(hp):
  moodel=Sequential()
  units=hp.Int('units',min_value=8,max_value=128,step=8)
  moodel.add(Dense(units=units,activation='relu',input_dim=8, name='dense_1'))
  moodel.add(Dense(1,activation='sigmoid', name='dense_2'))
  moodel.compile(optimizer=hp.Choice('optimizer',values=['adam','sgd']),loss='binary_crossentropy',metrics=['accuracy'])
  return moodel

In [54]:
tuner=kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5,directory='mydir')

Reloading Tuner from mydir/untitled_project/tuner0.json

In [33]:
tuner.search(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test))

In [55]:
tuner.get_best_hyperparameters()[0].values

{'units': 96, 'optimizer': 'adam'}

In [58]:
model=tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))